# Generated by Django 2.2.16 on 2021-01-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
