# Generated by Django 2.2.16 on 2021-01-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0002_auto_20210129_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapinfo',
            name='contact',
        ),
    ]
