# Generated by Django 2.2.16 on 2021-01-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0003_remove_mapinfo_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMapInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(max_length=1048)),
                ('longitude', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contapp.ContactInfo')),
            ],
            options={
                'db_table': 'contact_map_info',
            },
        ),
        migrations.DeleteModel(
            name='MapInfo',
        ),
    ]
